In [1]:
import numpy as np

# Array Creation
1.	Initialize an empty array with size 2X2.

In [7]:
empty_arr = np.empty((2,2))
print("Empty 2x2:\n", empty_arr)

Empty 2x2:
 [[3.42659709e-315 0.00000000e+000]
 [6.55810652e-310 6.55810650e-310]]


2.	Initialize an all one array with size 4X2.

In [8]:
ones_arr = np.ones((4,2))
print("Ones 4x2:\n", ones_arr)

Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3.	Return a new array of given shape and type, filled with fill value.

In [9]:
full_arr = np.full((3,3), 7)
print("Full 3x3 with 7:\n", full_arr)

Full 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


4.	Return a new array of zeros with same shape and type as a given array.

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
zeros_like_arr = np.zeros_like(arr)
print("Zeros like arr:\n", zeros_like_arr)

Zeros like arr:
 [[0 0 0]
 [0 0 0]]


5.	Return a new array of ones with same shape and type as a given array.

In [11]:
ones_like_arr = np.ones_like(arr)
print("Ones like arr:\n", ones_like_arr)

Ones like arr:
 [[1 1 1]
 [1 1 1]]


6.	For an existing list new_list = [1,2,3,4] convert to an numpy array.

In [12]:
new_list = [1,2,3,4]
np_arr = np.array(new_list)
print("Converted list:\n", np_arr)

Converted list:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1.	Create an array with values ranging from 10 to 49.

In [13]:
arr_range = np.arange(10,50)
print(arr_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2.	Create a 3X3 matrix with values ranging from 0 to 8.

In [14]:
matrix_3x3 = np.arange(9).reshape(3,3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3.	Create a 3X3 identity matrix.

In [15]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4.	Create a random array of size 30 and find the mean of the array.

In [16]:
rand_arr = np.random.random(30)
print("Mean:", rand_arr.mean())

Mean: 0.5258924771861943


5.	Create a 10X10 array with random values and find the minimum and maximum values.

In [17]:
rand_10x10 = np.random.random((10,10))
print("Min:", rand_10x10.min(), "Max:", rand_10x10.max())

Min: 0.002596038464902084 Max: 0.9996772285571046


6.	Create a zero array of size 10 and replace 5th element with 1.

In [18]:
zero_arr = np.zeros(10)
zero_arr[4] = 1
print(zero_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.	Reverse an array arr = [1,2,0,0,4,0].

In [19]:
arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

[0 4 0 0 2 1]


8.	Create a 2d array with 1 on border and 0 inside.

In [20]:
border_arr = np.ones((5,5))
border_arr[1:-1,1:-1] = 0
print(border_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9.	Create a 8X8 matrix and fill it with a checkerboard pattern.

In [21]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Array Operations

1.	Add the two array.

In [22]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [25]:
print(x + y)

[[ 6  8]
 [10 13]]


2.	Subtract the two array.

In [26]:
print(x - y)

[[-4 -4]
 [-4 -3]]


3.	Multiply the array with any integers of your choice.

In [27]:
print(x * 2)

[[ 2  4]
 [ 6 10]]


4.	Find the square of each element of the array.

In [28]:
print(np.square(x))

[[ 1  4]
 [ 9 25]]


5.	Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [29]:
print("v·w =", np.dot(v,w))
print("x·v =", np.dot(x,v))
print("x·y =", np.dot(x,y))

v·w = 219
x·v = [29 77]
x·y = [[19 22]
 [50 58]]


6.	Concatenate x(and)y along row and Concatenate v(and)w along column.

In [30]:
print("Concatenate x & y (rows):\n", np.concatenate((x,y), axis=0))
print("Concatenate v & w (columns):\n", np.column_stack((v,w)))

Concatenate x & y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v & w (columns):
 [[ 9 11]
 [10 12]]


7.	Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [31]:
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("Error:", e)
    print("Reason: x is 2D, v is 1D shapes don’t match.")

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D, v is 1D → shapes don’t match.


# Matrix Operation


In [32]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

1.	Prove A.A−1 = I.

In [36]:
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^-1:\n", identity)

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2.	Prove AB ̸= BA.

In [37]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB == BA ?", np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA ? False


3.	Prove (AB)T: = BT*AT .

In [39]:
lhs = (AB).T
rhs = np.dot(B.T, A.T)
print("(AB)^T:\n", lhs)
print("B^T A^T:\n", rhs)
print("LHS and RHS Equal?", np.allclose(lhs, rhs))

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
LHS and RHS Equal? True


•	Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9


In [49]:
# Coefficient matrix
coeff = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])

const = np.array([-1, -3, 9])

solution = np.linalg.solve(coeff, const)
print("Solution (x, y, z):", solution)

# Solving using inverse method explicitly
coeff_inv = np.linalg.inv(coeff)
solution_inv = np.dot(coeff_inv, const)
print("Solution via inverse:", solution_inv)

Solution (x, y, z): [ 2.  1. -2.]
Solution via inverse: [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?

In [48]:
import time

# Size of arrays
size = 1000000

# Python lists
list1 = list(range(size))
list2 = list(range(size))

# NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

# 1. Element-wise Addition
start = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
print("Python list addition time:", time.time() - start)

start = time.time()
np_add = arr1 + arr2
print("NumPy addition time:", time.time() - start)

# 2. Element-wise Multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
print("Python list multiplication time:", time.time() - start)

start = time.time()
np_mul = arr1 * arr2
print("NumPy multiplication time:", time.time() - start)

# 3. Dot Product
start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
print("Python list dot product time:", time.time() - start)

start = time.time()
dot_np = np.dot(arr1, arr2)
print("NumPy dot product time:", time.time() - start)

# 4. Matrix Multiplication
size = 200
list_matrix1 = [[i for i in range(size)] for _ in range(size)]
list_matrix2 = [[i for i in range(size)] for _ in range(size)]

start = time.time()
result_list = [[sum(a*b for a,b in zip(row,col)) for col in zip(*list_matrix2)] for row in list_matrix1]
print("Python matrix multiplication time:", time.time() - start)

np_matrix1 = np.arange(size*size).reshape(size,size)
np_matrix2 = np.arange(size*size).reshape(size,size)

start = time.time()
result_np = np.dot(np_matrix1, np_matrix2)
print("NumPy matrix multiplication time:", time.time() - start)

Python list addition time: 0.1244053840637207
NumPy addition time: 0.0032286643981933594
Python list multiplication time: 0.1184849739074707
NumPy multiplication time: 0.006958723068237305
Python list dot product time: 0.10775208473205566
NumPy dot product time: 0.0024161338806152344
Python matrix multiplication time: 0.7123208045959473
NumPy matrix multiplication time: 0.008358955383300781
